# .github/workflows/main.yaml
# Copyright 2026 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

permissions: {}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with: { persist-credentials: false }
      - uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7
        with: { cache-dependency-glob: noxfile.py }
      - run: ./noxfile.py
      # yamllint disable-line rule:line-length
      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: main
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
        id: deployment
    permissions:
      contents: read
      pages: write
      id-token: write
  renovate-config-validator:
    # yamllint disable-line rule:line-length
    uses: maxwell-k/dotlocalslashbin/.github/workflows/renovate.yaml@632255b6626fff16a0b5c25ec0b1210e46763e65 # v0.0.26
  zizmor:
    runs-on: ubuntu-24.04
    # https://github.com/zizmorcore/zizmor-action#permissions
    permissions: { security-events: write }
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with: { persist-credentials: false }
      # yamllint disable-line rule:line-length
      - uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0
