# .github/workflows/main.yaml
# Copyright 2026 Keith Maxwell
# SPDX-License-Identifier: CC0-1.0

on: # yamllint disable-line rule:truthy
  push: { branches: [main] }
  pull_request: { branches: [main] }
  workflow_dispatch:

permissions: {}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with: { persist-credentials: false }
      - uses: astral-sh/setup-uv@e06108dd0aef18192324c70427afc47652e63a82 # v7
        with: { cache-dependency-glob: noxfile.py }
      - run: ./noxfile.py
      # yamllint disable-line rule:line-length
      - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: main
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
        id: deployment
    permissions:
      contents: read
      pages: write
      id-token: write
  renovate-config-validator:
    # yamllint disable-line rule:line-length
    uses: maxwell-k/dotlocalslashbin/.github/workflows/renovate.yaml@d1558d04ad82861ead2cce45fb850a05c47e4fc7 # v0.0.27
  zizmor:
    runs-on: ubuntu-24.04
    # https://github.com/zizmorcore/zizmor-action#permissions
    permissions: { security-events: write }
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with: { persist-credentials: false }
      # yamllint disable-line rule:line-length
      - uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2
